name: apply

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/apply.yaml
      - *.tf
      - *.hcl

jobs:
  apply:
    runs-on: ubuntu-latest

    env: 
      COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform apply
        run: |
          terraform apply \
            -auto-approve \
            -var='project_env=prod' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'
