name: lint

on:
  pull_request:
    paths:
      - .github/actions/setup/action.yaml
      - .github/workflows/lint.yaml
      - '**.tf'
      - '**.hcl'

jobs:
  lint:
    runs-on: ubuntu-latest

    env: 
      COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Terraform format
        run: terraform fmt -recursive -check

      - name: Terraform validate
        run: terraform validate
