name: preview

on:
  pull_request:
    paths:
      - .github/actions/setup/action.yaml
      - .github/workflows/preview.yaml
      - '**.tf'
      - '**.hcl'

jobs:
  preview:
    runs-on: ubuntu-latest

    env: 
      COCKROACH_API_KEY: ${{ secrets.COCKROACH_API_KEY }} 
      TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Terraform plan
        run: |
          terraform plan \
            -var='project_env=prev' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'

      - name: Terraform apply
        run: |
          terraform apply \
            -auto-approve \
            -var='project_env=prev' \
            -var='sql_user_password=${{ secrets.COCKROACH_SQL_USER_PASSWORD }}'
